version: '3.8'

services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    ports:
      - "5000:3000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./new-api-data:/data
    restart: unless-stopped